### PR TITLE
docs: specify that pixel coordinates of hotspot are rounded to the floor

### PR DESCRIPTION
**Pull request by jinliu**
Since we now have a raw API, we shall specify how this is calculated, so users of the raw API can do the same in their rendering code.

### CODE REVIEW

**Comment by jinliu** [comment]
TBH, I'm unsure if we should round to the floor, or to the nearest. The former is more prone to precision problems, where instead of 0.36*100 = 36.00000 -> 36, you get 35.99998 -> 35.

**Comment by vaxerski** [comment]
std::round would make more sense indeed

**Comment by vaxerski** [comment]
I've made the lib round.

**Comment by jinliu** [comment]
Changed the doc accordingly.

**Review by vaxerski — APPROVED** [review]
thanks!

**Pull request merged**
